server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.31.3.147:3100/loki/api/v1/push
    timeout: 60s
    backoff_config:
      min_period: 1s
      max_period: 30s
      max_retries: 5
    batchwait: 10s
    batchsize: 1048576

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: mysql-server-logs
          host: mysql-server
          __path__: /var/log/*log

  - job_name: mysql-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mysql-logs
          host: mysql-server
          __path__: /var/lib/mysql/*.log