# roles/nginx/tasks/main.yml
---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy index.html from template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Start nginx service
  command: systemctl start nginx
  ignore_errors: yes

- name: Enable nginx service
  command: systemctl enable nginx
  ignore_errors: yes