apiVersion: batch/v1
kind: Job
metadata:
  name: hello-eks-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: hello-job
    spec:
      containers:
      - name: hello-container
        image: busybox:latest
        command: 
        - /bin/sh
        - -c
        - |
          echo "Hello from EKS!"
          echo "Job started at: $(date)"
          echo "Running in namespace: $POD_NAMESPACE"
          echo "Pod name: $HOSTNAME"
          echo "Kubernetes version info:"
          echo "Node: $NODE_NAME"
          sleep 10
          echo "Job completed successfully at: $(date)"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      restartPolicy: Never
  backoffLimit: 3