# playbooks/nginx.yml
---
- name: Configure nginx on servers
  hosts: servers
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Include nginx role
      include_role:
        name: nginx
      tags: nginx

  post_tasks:
    - name: Display nginx configuration summary
      debug:
        msg:
          - "Nginx configured on: {{ inventory_hostname }}"
          - "Web server is running on port 80"
      tags: info