name: CI/CD Pipeline with Monitoring

on:
  push:
    branches: [ pipeline-optimization ]
  pull_request:
    branches: [ pipeline-optimization ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Enable pip caching

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            libffi-dev \
            libssl-dev \
            gcc \
            make

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir cython
          # Install PyYAML with specific build flags to avoid Cython issues
          PYTHONPATH='' CFLAGS="-O2" pip install --no-cache-dir --no-build-isolation pyyaml==5.4.1
          pip install --no-cache-dir docker-compose

      - name: Check Docker Compose version
        run: |
          docker compose version || docker-compose version

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test commands here

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Add your deployment commands here

      - name: Monitoring setup
        run: |
          echo "Setting up monitoring..."
          # Add your monitoring configuration here
