name: CI/CD Pipeline with Monitoring

on:
  push:
    branches: [ pipeline-optimization ]
  pull_request:
    branches: [ pipeline-optimization ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            libffi-dev \
            libssl-dev \
            gcc \
            make \
            libyaml-dev  # Ajouté pour PyYAML

      - name: Create requirements file
        run: |
          cat > requirements.txt << EOF
          cython>=3.0.11
          pyyaml==5.4.1
          docker-compose
          EOF

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt || \
          (echo "⚠️ Première installation échouée, tentative avec flags spécifiques..." && \
          CFLAGS="-O2" pip install --no-cache-dir --no-build-isolation pyyaml==5.4.1)

      - name: Verify PyYAML installation
        run: |
          python -c "import yaml; print('PyYAML version:', yaml.__version__)"

      - name: Check Docker Compose version
        run: |
          docker compose version || docker-compose version

      - name: Run tests
        run: |
          echo "Running tests..."
          # Ajoute ici tes commandes de test

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Ajoute ici tes commandes de déploiement

      - name: Monitoring setup
        run: |
          echo "Setting up monitoring..."
          # Ajoute ici ta configuration de monitoring
